body:
  - type: dropdown
    attributes:
      name: max_search_results
      label: 'Max results:'
      defaultValue: 10
      options:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30
  - type: checkbox
    attributes:
      name: download_thumbs
      label: 'Download Thumbnails:'
      defaultValue: "true"
      description: Downloading thumbnails can slow down results